---
title: "AirQualityandEducation"
author: "Grace Lewin"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```



```{r}
education <- read_csv(here("data", "Education_2015_2019.csv")) %>% 
  clean_names() %>% 
  select(fips, county, x2013_rural_urban_continuum_code, 
         not_completing_high_school_2015_2019, completing_high_school_2015_2019,
         completing_some_college_2015_2019, completing_college_2015_2019) %>% 
  separate(col = county, into = c("county", "state"), sep = ",")

ca_aqi_2015 <- read_csv(here("data", "daily_aqi_by_county_2015.csv")) %>% 
  clean_names() %>% 
  filter(state_name == "California") %>% 
  rename(county = county_name)

ca_aqi_2016 <- read_csv(here("data", "daily_aqi_by_county_2016.csv")) %>% 
  clean_names() %>% 
  filter(state_name == "California") %>% 
  rename(county = county_name)

ca_aqi_2017 <- read_csv(here("data", "daily_aqi_by_county_2017.csv")) %>% 
  clean_names() %>% 
  filter(state_name == "California") %>% 
  rename(county = county_name)

ca_aqi_2018 <- read_csv(here("data", "daily_aqi_by_county_2018.csv")) %>% 
  clean_names() %>% 
  filter(state_name == "California") %>% 
  rename(county = county_name)

ca_aqi_2019 <- read_csv(here("data", "daily_aqi_by_county_2019.csv")) %>% 
  clean_names() %>% 
  filter(state_name == "California") %>% 
  rename(county = county_name)

ca_aqi_all <- rbind(ca_aqi_2015, ca_aqi_2016, ca_aqi_2017, ca_aqi_2018, ca_aqi_2019) %>% 
  mutate(date = as.Date(date))

aqi_education <- left_join(ca_aqi_all, education) %>% 
  rename(nchs = not_completing_high_school_2015_2019) %>% 
  rename(chs = completing_high_school_2015_2019) %>% 
  rename(csc = completing_some_college_2015_2019) %>% 
  rename(cc = completing_college_2015_2019)
  
aqi_education$nchs <- as.numeric(sub("%", "", aqi_education$nchs))
aqi_education$chs <- as.numeric(sub("%", "", aqi_education$chs))
aqi_education$csc <- as.numeric(sub("%", "", aqi_education$csc))
aqi_education$cc <- as.numeric(sub("%", "", aqi_education$cc))


```

# Poverty

```{r}
ca_poverty_2019 <- read_csv(here("data", "ca_poverty_2019.csv")) %>% 
  select(fips, county, ruc_code, percent, lowerbound, upperbound) %>% 
  rename(poverty_perc = percent)

aqi_poverty <- left_join(ca_aqi_2019, ca_poverty_2019, by = "county")

aqi_poverty_avg_aqi <- aqi_poverty %>% 
  group_by(county, poverty_perc, ruc_code) %>% 
  summarise(mean_aqi = mean(aqi))
```


## Join poverty dataset with aqi and education

```{r}
aqi_education_poverty <- left_join(aqi_education, ca_poverty_2019)

aqi_education_poverty_avg_aqi <- aqi_education_poverty %>% 
  group_by(county, poverty_perc, ruc_code, nchs, chs, csc, cc) %>% 
  summarise(mean_aqi = mean(aqi))
```


```{r}
aqi_education_avg_aqi <- aqi_education %>% 
  group_by(county, nchs, chs, csc, cc) %>% 
  summarise(mean_aqi = mean(aqi))
```



```{r}
ggplot(aqi_education_avg_aqi, aes(x = nchs, y = mean_aqi)) +
  geom_point() +
  labs(title = "County mean AQI vs Not Completing High School") +
  geom_text(aes(label=county),hjust=0, vjust=1) +
  geom_smooth(method='lm', formula= y~x, color="lightcoral", se=T, size=1.5) +
  theme_minimal()

mod <- lm(mean_aqi ~ nchs, data =aqi_education_avg_aqi)
summary(mod)
```


```{r}
ggplot(aqi_education_avg_aqi, aes(x = chs, y = mean_aqi)) +
  geom_point() +
  geom_text(aes(label=county),hjust=0, vjust=1) +
  geom_smooth(method='lm', formula= y~x, color="lightcoral", se=T, size=1.5) +
  theme_minimal()

mod <- lm(mean_aqi ~ chs, data =aqi_education_avg_aqi)
summary(mod)

```

```{r}
ggplot(aqi_education_avg_aqi, aes(x = csc, y = mean_aqi)) +
  geom_point() +
  geom_text(aes(label=county),hjust=0, vjust=1) +
  geom_smooth(method='lm', formula= y~x, color="lightcoral", se=T, size=1.5) +
  theme_minimal()

mod <- lm(mean_aqi ~ csc, data =aqi_education_avg_aqi)
summary(mod)

```


```{r}
ggplot(aqi_education_avg_aqi, aes(x = cc, y = mean_aqi)) +
  geom_point() +
  labs(title = "County Mean AQI vs Completing College 2015-2019") +
  geom_text(aes(label=county),hjust=0, vjust=1) +
  geom_smooth(method='lm', formula= y~x, color="lightcoral", se=T, size=1.5) +
  theme_minimal()

mod <- lm(mean_aqi ~ cc, data =aqi_education_avg_aqi)
summary(mod)

```





# Poverty and AQI


```{r}
ggplot(aqi_poverty_avg_aqi, aes(x = poverty_perc, y = mean_aqi)) +
  geom_point() +
  geom_text(aes(label=county),hjust=0, vjust=1) +
  geom_smooth(method='lm', formula= y~x, color="lightcoral", se=T, size=1.5) +
  theme_minimal()

mod <- lm(mean_aqi ~ poverty_perc, data =aqi_poverty_avg_aqi)
summary(mod)
summary(mod)$r.squared
```

# Rural areas and AQI

```{r}
ggplot(aqi_poverty_avg_aqi, aes(x = ruc_code, y = mean_aqi)) +
  geom_point() +
  geom_text(aes(label=county),hjust=0, vjust=1) +
  geom_smooth(method='lm', formula= y~x, color="lightcoral", se=T, size=1.5) +
  theme_minimal()

mod <- lm(mean_aqi ~ ruc_code, data =aqi_poverty_avg_aqi)
summary(mod)
summary(mod)$r.squared
```


```{r}
mod <- lm(mean_aqi ~ ruc_code + poverty_perc, data =aqi_poverty_avg_aqi)
summary(mod)
#summary(mod)$r.squared
```




```{r}
mod <- lm(mean_aqi ~ nchs + poverty_perc, data =aqi_education_poverty_avg_aqi)
summary(mod)
summary(mod)$r.squared
```

